### ISSUE TITLE
Is there a publicly viewable instance of blin available?

### ISSUE THREAD

**Issue by deefco** [Raku/Blin#3]
Or is everybody required to run their own

**Comment by AlexDaniel** [comment]
Sorry, missed that ticket somehow!

No, there is no publicly viewable instance. However, I file tickets like this from time to time: https://github.com/rakudo/rakudo/issues/2451

IMO it's better to have it based on gists (instead of a separate webapp). One issue I have with Toaster is that its results were thrown away for previous months (making links to it from previous tickets pretty much useless).

See also https://github.com/perl6/Blin/issues/4.

**Comment by AlexDaniel** [comment]
Also, note that Blin is not just a thing that runs for the whole ecosystem. You can use it bisect individual modules. So for some purposes web based interface is possibly not wanted at all.

**Comment by AlexDaniel** [comment]
@deefco Hello! While there's still no public instance, we use data from Blit to populate [ecosystem-unbitrot](https://github.com/perl6/ecosystem-unbitrot/issues) repo. In my opinion that is even better (it even pings authors and links to previous tickets). Example issue: https://github.com/perl6/ecosystem-unbitrot/issues/474

I think that resolves this issue, so I'm going to close this. But please let me know if it doesn't and I'll try to cover your use case.
